Fix for Log Bug
Fixed logging bug, uninitialized Log bytes.buffer{}.

diff --git a/testcoverage b/testcoverage
--- a/testcoverage
+++ b/testcoverage
@@ -11,9 +11,11 @@ echo "mode: set" > acc.out
 fail=0
 
 # Standard go tooling behavior is to ignore dirs with leading underscores
-for dir in $(find . -maxdepth 10 -not -path './.git*' -not -path './vendor*' -not -path './payload*' -not -path '*/_*' -type d);
+for dir in $(find . -maxdepth 10 -not -path './.?*' -not -path './vendor/*' -not -path './payload*' -not -path '*/_*' -type d);
 do
   if ls $dir/*.go &> /dev/null; then
+    # go test -v $dir || fail=1
+    #
     go test -coverprofile=profile.out $dir || fail=1
     if [ -f profile.out ]
     then
